
baseURL = "https://camrub-ops.github.io/videocast/"
languageCode = "es"
title = "Mi Video Podcast"
theme = "minimal"

[params]
  description = "Video‑podcast sobre tecnología y cultura digital."
  author = "Xavi74"
  cover = "/img/cover.jpg"

[outputs]
  home = ["HTML", "RSS", "podcast"]
  section = ["HTML", "RSS"]

[outputFormats]
  [outputFormats.podcast]
    name = "podcast"
    mediaType = "application/rss+xml"
    baseName = "feed"
    isPlainText = false
